name: apotik_pulosari
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 60.0.0+60

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^3.4.2
  url_launcher: ^5.4.0
  # firebase_auth: 0.15.5+2
  http: ^0.12.2
  bloc: ^6.0.0
  flutter_bloc: ^6.0.1
  rxdart: ^0.24.1
  provider: ^4.0.5
  splashscreen: ^1.2.0
  mdi: ^4.0.0
  dotted_border: ^1.0.5
  flutter_masked_text: ^0.8.0
  equatable: ^1.2.0
  intl: ^0.16.1
  page_transition: "^1.1.6"
  indonesia: ^1.0.1
  shared_preferences: ^0.5.8
  get_storage: ^1.2.1
  qrscan: ^0.2.17
  curved_navigation_bar: ^0.3.4
  shimmer: ^1.1.1
  hive: ^1.1.0+1
  hive_flutter: ^0.2.1
  hive_generator: ^0.5.2
  build_runner: ^1.7.0
  currency_text_input_formatter: ^0.3.1
  connectivity: ^2.0.2
  flutter_spinkit: "^4.1.2"
  dio: ^3.0.10
  flutter_slidable: ^0.5.7
  date_range_picker: ^1.0.6
  charts_flutter: ^0.9.0
  sliding_up_panel: ^1.0.2
  open_file: ^2.1.1
  syncfusion_flutter_core: ^18.4.49
  syncfusion_flutter_datagrid: ^18.4.49-beta
  syncfusion_flutter_xlsio: ^18.4.49-beta
  syncfusion_flutter_pdf: ^18.4.49-beta
  # new_version: ^0.0.5
  month_picker_dialog: ^0.3.3
  jiffy: ^3.0.1
  image_picker: ^0.6.7+22
  path_provider: ^1.6.28
  flutter_image_compress: ^0.7.0

  # simple_permissions: ^0.1.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icons/login_page/login.png
    - assets/images/icons/home_page/account.png
    - assets/images/icons/home_page/purchase.png
    - assets/images/icons/home_page/so.png
    - assets/images/icons/home_page/pobb.png
    - assets/images/icons/home_page/category.png
    - assets/images/icons/home_page/unit.png
    - assets/images/icons/home_page/item.png
    - assets/images/icons/home_page/supplier.png
    - assets/images/icons/home_page/patient.png
    - assets/images/icons/home_page/doctor.png
    - assets/images/icons/home_page/user.png
    - assets/images/icons/home_page/regular.png
    - assets/images/icons/home_page/recipe.png
    - assets/images/icons/home_page/formula.png
    - assets/images/icons/home_page/lab.png
    - assets/images/icons/home_page/netto.png
    - assets/images/icons/home_page/close.png
    - assets/images/icons/home_page/wallet.png
    - assets/images/icons/home_page/pobb.png
    - assets/images/icons/home_page/purchase.png
    - assets/images/icons/home_page/itemin.png
    - assets/images/icons/home_page/itemout.png
    - assets/images/icons/home_page/report.png
    - assets/images/icons/title_page/create.png
    - assets/images/icons/item_page/item.png
    - assets/images/icons/sales_page/cart.png
    - assets/images/icons/sales_page/recipe.png
    - assets/images/icons/resp_page/success.png
    - assets/images/icons/resp_page/progress.png
    - assets/images/icons/state_page/noresult.png
    - assets/images/icons/resp_page/connection.png
    - assets/images/icons/resp_page/confirmation.png
    - assets/images/icons/state_page/noresult.png
    - assets/images/icons/state_page/emptycart.png
    - assets/images/logo-white.png
    - assets/images/logo.png
    - assets/images/background/circle_fc_lg.png
    - assets/images/background/circle_fc_md.png
    - assets/images/background/dounat_fc_lg.png
    - assets/images/background/dounat_fc_sm.png
    - assets/images/background/panel_slide_up.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
